### ISSUE TITLE
how to reload menu from any controller?(want to update user image and name top of table)

### ISSUE THREAD

**Issue by PramodShukla10** [luannguyenkhoa/LNSideMenu#17]

**Comment by PramodShukla10** [comment]
i want update user image and name

**Comment by luannguyenkhoa** [comment]
Hi man,

![Demo](https://cloud.githubusercontent.com/assets/13121441/19177074/0cd3415e-8c70-11e6-8082-5057bf406e42.gif)
Look like you're using the custom menu instead of detault one, right? 
As the code example, we have LeftMenuTableViewController for custom menu, there are many approaches to communicate with it such as Notification, Observer,... 
Basically, you can manage to manually update these two fields yourself by sending new data to this viewcontroller and force it to update corresponding fields from anywhere in your app.

**Comment by PramodShukla10** [comment]
Ok thanks

**Comment by luannguyenkhoa** [comment]
Sorry for late reply.

It's just an iOS basic flow control, particularly in viewcontrollers communication. Notification, observer, delegate methods,... are appropriated to your scenario. 
Using your custom menu means that you do have the ability completely to manage and control it yourself, out of lib supports.

**Comment by iamshezad** [comment]
@PramodShukla10 i think using the below code you can reload from any viewcontroller in the example project
` if let menu = sideMenuManager?.instance()?.menu?.customMenu as? LeftMenuTableViewController {
 menu.menuTableView.reloadData()
}`

@luannguyenkhoa

**Comment by iamshezad** [comment]
@luannguyenkhoa Yes, using the menu instance he can access any objects in the class  LeftMenuTableViewController
