### ISSUE TITLE
Not able to get Second design as shown on readme

### ISSUE THREAD

**Issue by GabbyRahul** [luannguyenkhoa/LNSideMenu#3]
![0cd3415e-8c70-11e6-8082-5057bf406e42](https://cloud.githubusercontent.com/assets/25679340/22916616/8d51ae88-f2a5-11e6-93e5-4fe7c5f04dea.gif)

How to get this design ??
According to your sample code we made this design in LeftMenuTableViewController and we call this in SMNavigationController but still getting that black and white  curve design...
please help me !!!

**Comment by luannguyenkhoa** [comment]
Hi @GabbyRahul,

Sorry for late reply. I was busy these days at my work.
Regarding to your issues, please ensure that you have initialized the custom menu by using code as below: 
`LNSideMenu(navigation: self, menuPosition: position, customSideMenu: yourMenuInstance)`
Having a look at this function `func initialCustomMenu(pos position: Position)` in `SMNavigationController` for more details.

Don't use code like this: `LNSideMenu(sourceView: self.view, menuPosition: .left, items: ["abc", "xyz"])`, otherwise you will get the default design that is black and white curve design.

Let me know if any.
Thanks.
