### ISSUE TITLE
Text for the latest rows doesn't show correctly

### ISSUE THREAD

**Issue by YassminAbdallah** [luannguyenkhoa/LNSideMenu#4]
![simulator screen shot apr 26 2017 4 35 32 pm](https://cloud.githubusercontent.com/assets/11721665/25440069/8f58276c-2a9e-11e7-9d63-1a676de8e02a.png)

Hello,

when i tried the example code in iphone 7 plus the text for the last row doesn't show correctly, it's kinda shifted to right, so i was wondering how i can resolve this.

another thing if i want to add an image how this can be done ?

Thanks a lot.

**Comment by luannguyenkhoa** [comment]
thanks for reporting the issues.
Regarding to the first one, which iOS and XCode version are you using? (Currently, this lib still works fine on swift 3, iOS 10.2, xcode 8.2.1)

**Comment by luannguyenkhoa** [comment]
Thanks for reporting the issue.

Could you let me know which iOS version and swift version you are using? I have just rechecked the issue on ip7 plus iOS 10.2 and swift 3.0, it still works fine at my end.

Regarding to your question, you mean that you wanna use an image instead of black curve background, right? If yes, unfortunately, the currently doesn't support this feature. Anw, if you can show me the design that you expected, I will schedule to implement it if possible.

**Comment by YassminAbdallah** [comment]
Hello Thanks for your reply,

 I'm using Xcode 8.3.1 swift 3.1, this issue raised on iphone7 plus simulator, please try to write two words rather than one in the last cell. 

And for my question, I'm sorry I didn't explain it right, I want to add an image to the cell, before the text, as it doesn't appear when i added one. 

Thanks a lot.
