### ISSUE TITLE
How Can i use this with Objective c

### ISSUE THREAD

**Issue by nikhildhamsaniya** [luannguyenkhoa/LNSideMenu#6]

**Comment by luannguyenkhoa** [comment]
You should follow this discussion in order to import a swift pod in ObjC project: https://stackoverflow.com/questions/24102104/how-to-import-swift-code-to-objective-c
I haven't tried to use this lib in an ObjC project yet, but I think it should work.

Get back to me if any. 
Thanks for your attention.
